import type { APIRoute } from 'astro';
import { withBase } from '../lib/path';

// robots.txt generated at build time so the Sitemap directive always points at
// the live origin (Astro.site) and the correct base path, instead of a
// hardcoded placeholder domain. Note: on a GitHub Pages *project* site this is
// served at <base>/robots.txt; a custom domain (base `/`) is required for it to
// appear at the origin root where crawlers look by default.
export const GET: APIRoute = ({ site }) => {
  if (!site) return new Response('', { headers: { 'Content-Type': 'text/plain' } });
  const sitemap = new URL(withBase('/sitemap-index.xml'), site).href;
  const body = `User-agent: *
Allow: /
Disallow: ${withBase('/admin/')}
Disallow: ${withBase('/editorial')}

# Sitemap is generated by @astrojs/sitemap at build time.
Sitemap: ${sitemap}
`;
  return new Response(body, { headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
};
